version: "3.7"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/logs:/logs

  ghost:
    image: ghost:3
    restart: unless-stopped
    environment:
      NODE_ENV: production
      url: http://localhost
      # mail__options__service: Mailgun
      # mail__options__auth__user: you@example.com
      # mail__options__auth__pass: super-secret-password
    volumes:
      - $PWD/content:/var/lib/ghost/content
